# Robot name goes here
robot_1:

  # default controller
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Controller 1
  rear_left_controller:
    type: velocity_controllers/JointVelocityController
    joint: rotary_left
    pid : {p: 10.0 , i: 1.0, d: 1.0}  #Enter your pid values eg. {p: 100.0 , i: 0.0 , d: 0.0} 

  # Controller 2
  rear_right_controller:
    type: velocity_controllers/JointVelocityController
    joint: rotary_right
    pid : {p: 10.0 , i: 1.0, d: 1.0} # Enter your pid values eg. {p: 100.0 , i: 0.0 , d: 0.0} 
  # Controller 3
  steer_left_controller:
    type: effort_controllers/JointPositionController
    joint: steer_left
    pid : {p: 10.0 , i: 1.0, d: 1.0}
  # Controller 4
  steer_right_controller: 
    type: effort_controllers/JointPositionController
    joint: steer_right
    pid : {p: 10.0 , i: 1.0, d: 1.0} # Enter your pid values eg. {p: 100.0 , i: 0.0 , d: 0.0} 
    
  


 
